name: Deploy Franklin.jl Site

on:
  push:
    branches:
      - main  # Change this to your default branch if different
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'  # Use the version of Julia you are using

      - name: Install Franklin
        run: |
          julia -e 'using Pkg; Pkg.add("Franklin")'
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Build site
        run: |
          pwd
          ls
          cd docs
          julia -e 'using Pkg; Pkg.add("Franklin")'
          julia --project=. -e 'using Pkg; Pkg.instantiate()'
          julia --project=. -e 'using Franklin; optimize()'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "__site/"         

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
